Banao_task_1/urls.py
from django.contrib import admin
from django.urls import path
from medicine.views import login, dashboard, logout, create, delete, edit
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, name="login"),
    path('', dashboard, name="dashboard"),
    path('create/post/', create, name="create"),
    path('edit/post/<int:id>/', edit, name="edit"),
    path('delete/post/<int:id>/', delete, name="delete"),
    path('logout/', logout, name='logout'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

medicine/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)
from django.conf import settings
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, username, password=None, **extra_field):
        if not username:
            raise ValueError('User must have username address.')
        user = self.model(username=username, **extra_field)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, password):
        user = self.create_user(username, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(verbose_name="First name", max_length=50)
    last_name = models.CharField(verbose_name="Last name", max_length=50)
    picture = models.ImageField(verbose_name="Image", upload_to="Users/", blank=True, null=True)
    username = models.CharField(verbose_name="Username", max_length=50, unique=True)
    email = models.EmailField(verbose_name="Email", unique=True)
    address = models.TextField(verbose_name="Adress(line1, city, state, pincode)", max_length=500)
    class type_choise(models.TextChoices):
        Patient = 'P', _('Patient')
        Doctor = 'D', _('Doctor')
    type = models.CharField(
        verbose_name="Type", choices=type_choise.choices, default=type_choise.Patient, max_length=2)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'


class Categories(models.Model):
    name = models.CharField(verbose_name="Category name", max_length=255)
    date = models.DateTimeField(verbose_name="Auto created date", auto_now_add=True)

    def __str__(self):
        return self.name


class Blog(models.Model):
    created = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Created user")
    title = models.CharField(verbose_name="Title", max_length=255)
    image = models.ImageField(verbose_name='Image', upload_to='Posts/', editable=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE, verbose_name="categories")
    summary = models.CharField(verbose_name='Summary', max_length=255)
    content = models.TextField(verbose_name="Content", max_length=1000)
    drafted = models.BooleanField(default=False, verbose_name='Draft')
    views = models.PositiveIntegerField(verbose_name="Views", default=0, blank=True, null=True)
    date = models.DateTimeField(verbose_name="Auto created date", auto_now_add=True)


    def __str__(self):
        return self.title

medicine/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib import messages
from .models import User, Categories, Blog
import os

def login(request):
    if request.POST:
        if "signin" in request.POST:
            try:
                username = request.POST.get('username')
                password = request.POST.get('password')
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    auth_login(request, user)
                    messages.success(request, f"Hello {username}")
                    return redirect('dashboard')
                else:
                    messages.error(request, "Something is wrong")
            except:
                messages.error(request, "Something is wrong")
        elif "signup" in request.POST:
            try:
                data = request.POST
                if data.get('password1')==data.get('password2'):
                    try:                        
                        if len(request.FILES)==0:
                            picture = None
                        else:
                            _, file = request.FILES.popitem()
                            picture = file[0]
                        
                        user = User.objects.create_user(first_name=data.get('first_name'), last_name=data.get('last_name'),
                                            username=data.get('username'), password=data.get('password1'), picture=picture, email=data.get('email'), address=data.get('address'), type=data.get('type'))
                        auth_login(request, user)
                        # messages.success(request, f"Hello {user}")
                        return redirect('dashboard')
                    except:
                        messages.error(request, "Username or Email is exist")
                else:
                    messages.error(request, "Passwords are not similar")
            except:
                messages.error(request, "Something is wrong")
    return render(request, 'Login.html')

def dashboard(request):
    if not request.user.is_authenticated:
        return redirect('login')
    orderbylist = ['category', '-date']
    if request.user.type=="D":
        context = {
            "posts": Blog.objects.filter(drafted=False).order_by(*orderbylist) |Blog.objects.filter(drafted=True).order_by(*orderbylist)
        }
    else:
        context = {
            "posts": Blog.objects.filter(drafted=False).order_by(*orderbylist)
        }
    return render(request, "Dashboard.html", context=context)

def create(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.type!="D": return redirect('dashboard')
    if request.method == 'POST':
        data = request.POST
        title = data.get('title')
        category = data.get('category')
        summary = data.get('summary')
        content = data.get('content')
        drafted = 'drafted' in  data.keys()
        if len(request.FILES)==0:
            image = None
        else:
            _, file = request.FILES.popitem()
            image = file[0]
        try:
            Blog.objects.create(created=User.objects.get(id=request.user.id), title=title, image=image, category=Categories.objects.get(id=category), 
                                      summary=summary, content=content, drafted=drafted)
            messages.success(request, f"{title} post created")
            return redirect('dashboard')
        except:
            messages.error(request, "Something is wrong!")
            return redirect('create')
    context = {
        'categories': Categories.objects.all().order_by('-date')
    }
    return render(request, 'create.html', context=context)

def edit(request, id):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.type!="D": return redirect('dashboard')
    try:
        if request.user == Blog.objects.get(id=id).created:
            if request.method == "POST":
                data = request.POST
                title = data.get('title')
                category = data.get('category')
                summary = data.get('summary')
                content = data.get('content')
                drafted = 'drafted' in  data.keys()
                if len(request.FILES)==0:
                    Blog.objects.filter(id=id).update(created=User.objects.get(id=request.user.id), title=title, category=Categories.objects.get(id=category), 
                                            summary=summary, content=content, drafted=drafted)
                    messages.success(request, f"{title} post edited")
                    return redirect('dashboard')
                else:
                    image = request.FILES['image']
                    a = Blog.objects.get(id=id)
                    os.remove(a.image.path)
                    Blog.objects.get(id=id).delete()
                    try:
                        Blog.objects.create(created=User.objects.get(id=request.user.id), title=title, image=image, category=Categories.objects.get(id=category), 
                                                summary=summary, content=content, drafted=drafted)
                        messages.success(request, f"{title} post edited")
                        return redirect('dashboard')
                    except:
                        messages.error(request, "Somethingbbjhbhbhb is wrong!")
                        return redirect('dashboard')
            a = Blog.objects.get(id=id)
            context = {
                'data': a,
                'categories': Categories.objects.all().order_by('-date'),
            }
            return render(request, 'edit.html', context=context)
    except:
        messages.error(request, "Something is wrong!")
        return redirect('dashboard')
    

def delete(request, id):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.type!="D": return redirect('dashboard')
    try:
        if request.user == Blog.objects.get(id=id).created:
            a = Blog.objects.get(id=id)
            os.remove(a.image.path)
            Blog.objects.get(id=id).delete()
            messages.success(request, f"{a.title} post deleted")
            return redirect('dashboard')
        else:
            messages.error(request, "Something is wrong!")
            return redirect('dashboard')
    except:
        messages.error(request, "Something is wrong!")
        return redirect('dashboard')

def logout(request):
    auth_logout(request)
    return redirect('login')

medicine/templates/Dashboard.html
{% load static %}
{% load my_functions %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <center>
    <h1 class="mt-5 mx-auto">{{ user.get_type_display }} {{ user.first_name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="{{ MEDIA_URL }}{{ user.picture.url }}" class="rounded-circle" width="50" alt="{{ user.first_name }}"></h1>
    </center>
    <div class="w-25 mt-5 mx-auto">{% if messages %} {% include 'message.html' %} {% endif %}</div>
    
    </div>
    {% if user.type == "D" %}
    <div class="w-100 p-3 col d-flex justify-content-center mt-5">
    <a href="{% url 'create' %}" class="btn btn-success btn-lg active" role="button" aria-pressed="true">Create post</a>
    </div>
    {% endif %} 
    <div class="col d-flex justify-content-center mt-5">
    {% if posts %}
    <div class="cards">
        {% for post in posts %}
            <div class="card mb-5" style="max-width: 50rem;">
                <img class="card-img-top" src="{{ MEIDA_URL }}{{ post.image.url }}" alt="Post image">
                <div class="card-body">
                    <h5 class="card-title"><strong>Title: </strong> {{ post.title }}</h5>
                    <p class="card-text"><strong>Summary: </strong> {{ post.summary | trunc }}</p>
                    <p class="card-text"><strong>Category: </strong> {{ post.category }}</p>
                    <p class="card-text"><strong>Drafted: </strong> {{ post.drafted }}</p>
                    <p class="card-text"><strong>Created by: </strong> {{ post.created }}</p>
                    {% if post.created.id == user.id %}
                        <a href="{% url 'edit' id=post.id %}" class="btn btn-info" role="button" aria-pressed="true">Edit</a>
                        <a href="{% url 'delete' id=post.id %}" class="btn btn-danger" role="button" aria-pressed="true">Delete</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    
    </div>
    <center><a href="{% url 'logout' %}" class="btn btn-outline-danger" role="button" aria-pressed="true">Logout</a></center>
</body>
</html>

medicine/templates/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<title>Login</title>
</head>
<body>
	{% if messages %} {% include 'message.html' %} {% endif %}

	<h2>Sign in/up Form</h2>
	<div class="container" id="container">
		<div class="form-container sign-up-container">
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<h1>Create Account</h1>
				
				<table>
					<tr>
						<td><label for="p">Patient &nbsp;&nbsp;&nbsp;</label></td>
						<td><label for="d">Doctor</label></td>
					</tr>
					<tr>
						<td><input type="radio" id="p" name="type" value="P" required></td>
						<td><input type="radio" id="d" name="type" value="D" required></td>
					</tr>
				</table>
				<input type="text" name="first_name", placeholder="First name" required/>
				<input type="text" name="last_name", placeholder="Last name" required/>
				<input type="email" name='email' placeholder="Email" required/>
				<input type="text" name="username" placeholder="Username" required/>
				<input type="password" name="password1" placeholder="Password" required/>
				<input type="password" name="password2" placeholder="Confirm Password" required/>
				<input type="file" name="image" accept="image/png, image/gif, image/jpeg"/>
				<input type="text" name="address" placeholder="Address(line1, city, state, pincode)" required/>

				<button name="signup" type="submit">Sign Up</button>
			</form>
		</div>
		<div class="form-container sign-in-container">
			<form method="POST">
				{% csrf_token %}
				<h1>Sign in</h1>
				<input type="text" name="username" placeholder="Username" required/>
				<input type="password" name="password" placeholder="Password" required/>
				<button name="signin" type="submit">Sign In</button>
			</form>
		</div>
		<div class="overlay-container">
			<div class="overlay">
				<div class="overlay-panel overlay-left">
					<h1>Welcome to our sign up page</h1>
					<p>if you have account please click sign in button</p>
					<button class="ghost" id="signIn">Sign In</button>
				</div>
				<div class="overlay-panel overlay-right">
					<h1>Welcome to our sign in page</h1>
					<p>if you don't have account please click sign up button</p>
					<button class="ghost" id="signUp">Sign Up</button>
				</div>
			</div>
		</div>
	</div>

	
	<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

medicine/templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create post</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <div class="container">
    <h1 class="w-25 mt-5 mx-auto">{{ user.get_type_display }} {{ user.first_name }}</h1>
    </div>
    <style>
        label {
            font-size: 25px;
            font-weight: 600;
        }
    </style>
    
    <form class="container mt-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="w-25 mx-auto">{% if messages %} {% include 'message.html' %} {% endif %}</div>
        <div class="form-group">
            <label for="title1">Title</label>
            <input type="text" class="form-control" name='title' id="title1" placeholder="Title">
        </div>
        <div class="form-group">
            <label for="image1">Blog image</label>
            <input type="file" name="image" class="form-control-file" id="image1" accept="image/png, image/gif, image/jpeg">
        </div>
        {% if 'categories' %}
        <div class="form-group">
            <label class="mr-sm-2" for="category1">Category</label>
            <select name="category" class="custom-select mr-sm-2" id="category1">
                <option selected>Choose category...</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        {% endif %}
        <div class="form-group">
            <label for="title2">Summary</label>
            <input type="text" class="form-control" name='summary' id="title2" placeholder="Summary">
        </div>
        <div class="form-grops">
            <textarea class="form-control" name="content" rows="5" placeholder="Content" spellcheck="false" style="position: relative;"></textarea>
        </div>
        
        <div class="form-group">
            <label class="form-check-label" for="drafted">Draft</label>
            <input class="form-check-input ml-3 mt-3" name='drafted' type="checkbox" value="" id="drafted">
        </div>
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url "dashboard" %}" class="btn btn-secondary">Cancel</a>
    </form>
</body>
</html>

medicine/templates/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create post</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <style>
        label {
            font-size: 25px;
            font-weight: 600;
        }
    </style>
    
    <form class="container mt-5" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="w-25 mx-auto">{% if messages %} {% include 'message.html' %} {% endif %}</div>
        <div class="form-group">
            <label for="title1">Title</label>
            <input type="text" class="form-control" name='title' id="title1" value="{{ data.title }}" placeholder="Title">
        </div>
        <div class="form-group">
            <label for="image1">Blog image</label>
            <input type="file" name="image" class="form-control-file" id="image1" value="{{ data.image.url }}" accept="image/png, image/gif, image/jpeg">
        </div>
        {% if 'categories' %}
        <div class="form-group">
            <label class="mr-sm-2" for="category1">Category</label>
            <select name="category" class="custom-select mr-sm-2" id="category1">
                <option>Choose category...</option>
                {% for category in categories %}
                <option value="{{ category.id }}" {% if data.category.id == category.id %} selected {% endif %}>{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        {% endif %}
        <div class="form-group">
            <label for="title2">Summary</label>
            <input type="text" class="form-control" name='summary' value="{{ data.summary }}" id="title2" placeholder="Summary">
        </div>
        <div class="form-grops">
            <textarea class="form-control" name="content" rows="5" placeholder="Content" spellcheck="false" style="position: relative;">{{ data.content }}</textarea>
        </div>
        
        <div class="form-group">
            <label class="form-check-label" for="drafted">Draft</label>
            <input class="form-check-input ml-3 mt-3" name='drafted' type="checkbox" value="" id="drafted" {% if data.drafted %}checked{% endif %}>
        </div>
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url "dashboard" %}" class="btn btn-secondary">Cancel</a>
    </form>
</body>
</html>

medicine/templates/message.html
	<ul class="messages">
		{% for message in messages %}
		{% if "success" == message.tags %}
			<div class="alerttt success">
				<span class="closebtn">×</span>  
				{{ message }}
			</div>
		{% else %}
			<div class="alerttt danger">
				<span class="closebtn">×</span>  
				{{ message }}
			</div>
		{% endif %}
		</div>
		{% endfor %}
	</ul>
	<style>
		.alerttt {
			padding: 5px;
			color: white;
			opacity: 0.83;
			transition: opacity 0.6s;
			margin-bottom: 15px;
            border-radius: 5px;
		}
		.alerttt.success {
			background-color: #04AA6D;
		}
        .alerttt.danger {
            background-color: #ff445c;
        }
		.alerttt {
		opacity: 1;
		transition: opacity 0.6s;
		}
		.closebtn {
			margin-left: 15px;
			color: white;
			font-weight: bold;
			float: right;
			font-size: 22px;
			line-height: 20px;
			cursor: pointer;
			transition: 0.3s;
		}
		.closebtn:hover {
			color: black;
		}
	</style>
	<script>
        var close = document.getElementsByClassName("closebtn");
        var i;
        for (i = 0; i < close.length; i++) {
        close[i].onclick = function(){
            var div = this.parentElement;
            div.style.opacity = "0";
            setTimeout(function(){ div.style.display = "none"; }, 600);
        }
        }
    </script>